### ISSUE TITLE
[Enigma] Нейминг

### ISSUE THREAD

**Issue by pavel-b-novikov** [nechakhin/nsudotnet#2]
camelCase в C# не используется так, как используете его вы.  Пожалуйста ознакомьтесь и исправьтесь: https://msdn.microsoft.com/en-us/library/xzf533w0(v=vs.71).aspx

**Comment by nechakhin** [comment]
Переименовал

**Comment by pavel-b-novikov** [comment]
Не переименовали

> public enum Mode { encrypt, decrypt };

**Comment by nechakhin** [comment]
Исправил
