### ISSUE TITLE
[Enigma] Потоки

### ISSUE THREAD

**Issue by pavel-b-novikov** [nechakhin/nsudotnet#3]
Не диспозятся. Копирование из потока в поток - говорил же не писать руками, использовать встроенные методы.  Переделывайте.

**Comment by nechakhin** [comment]
Копирование из потока в поток реализовал встроенными средствами
Close для потока вызывает Dispose внутри

**Comment by pavel-b-novikov** [comment]
Да ничего у вас не задиспозится если вместо ключа подсунуть невалидную строку.

**Comment by nechakhin** [comment]
Сделал с using, теперь все закроется
