### ISSUE TITLE
[Enigma] Файл ключей

### ISSUE THREAD

**Issue by pavel-b-novikov** [nechakhin/nsudotnet#6]
Я видимо не заметил какой цирк вы разводите вокруг файла ключей. Посмеялся, пофейспалмил. 
Там два массива байт. Черт побери, а вот можно придумать как-то более человечный способ сохранять и читать их?

**Comment by nechakhin** [comment]
Программа работает, выдавая в output.bin зашифрованный двоичный файл, и 
кладет рядом с этим файлом файл file.key.txt, в который помещает IV 
(initialization vector) и Key в формате base64

Разве не это делает моя программа?

И что Вы понимаете под "более человечный способ", если не трудно, дайте 
материал, где я могу это прочесть


5/9/2016 10:51 PM, Pavel Novikov пишет:

**Comment by pavel-b-novikov** [comment]
Все, углядел.
Вы просто как-то странно делаете, серьезно. Делаете BinaryWriter вокруг файла ключей, чтобы закинуть туда Encoding.UTF.GetBytes от результата перевода в base64. Вместо того чтобы просто сделать WriteLine через textwriter. Это какая-то стрельба себе по ногам, видимо, в попытке получить удовольствие. Я специально сразу сказал всем чтобы писали ключи в base64, чтобы не начали массив байт скидывать в файл через write и обрабатывать кодировку, но вы это сделали крайне странным способом.

**Comment by nechakhin** [comment]
Мне переделывать, или Вы приняли ее?
5/10/2016 1:09 AM, Pavel Novikov пишет:

**Comment by pavel-b-novikov** [comment]
Да черт уж с ним, принято. Но на будущее - не делайте так никогда на живых проектах.
